"""Emit every number the new manuscript section prints, as LaTeX macros.

The manuscript never hard-codes a result. It reads
``submission/generated_certrelex.tex``, which this script writes from
``enhanced/analysis/report.json`` and ``enhanced/results/``.  If the report is
missing or stale the macro file is not written and the LaTeX build fails on an
undefined control sequence -- which is the intended behaviour: a figure or a
table that no longer matches its data should stop the build, not print quietly.
"""
from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "analysis" / "report.json"
EXAMPLES = ROOT / "results" / "examples.json"
ENVIRONMENT = ROOT / "results" / "run_environment.json"
DEST = ROOT.parent / "Manuscrit" / "submission" / "generated_certrelex.tex"


def num(x, digits=4):
    if x is None:
        return "n/a"
    return f"{float(x):.{digits}f}"


def pct(x, digits=1):
    return f"{100 * float(x):.{digits}f}"


def main() -> int:
    for p in (REPORT, EXAMPLES, ENVIRONMENT):
        if not p.exists():
            raise SystemExit(f"missing input: {p}. Run the experiments first.")
    rep = json.loads(REPORT.read_text())
    ex = json.loads(EXAMPLES.read_text())
    env = json.loads(ENVIRONMENT.read_text())

    lines = [
        "% Generated by enhanced/analysis/make_macros.py. Do not edit by hand.",
        "% Every number below traces to enhanced/results/ via analysis/report.json.",
    ]

    emitted = {}

    def cmd(name, value):
        """Emit once. A repeated name with a different value is a real
        inconsistency in the report and stops the build rather than silently
        producing a LaTeX redefinition error later."""
        value = str(value)
        if name in emitted:
            if emitted[name] != value:
                raise SystemExit(
                    f"macro {name} would be defined twice with different values: "
                    f"{emitted[name]!r} then {value!r}"
                )
            return
        emitted[name] = value
        lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")

    # --- run configuration ------------------------------------------------
    cmd("crxInstances", env["n_instances"])
    cmd("crxShortlist", env["shortlist"])
    cmd("crxBudget", env["box_budget"])
    cmd("crxResolution", env["resolution"])
    cmd("crxFocalLevel", env["focal_level"])

    # --- E0 correctness ---------------------------------------------------
    c = rep["correctness"]
    cmd("crxOracleDraws", f"{c['oracle_draws']:,}".replace(",", ","))
    cmd("crxOracleViolations", c["oracle_violations"])
    cmd("crxReplayLeaves", f"{c['leaves_replayed']:,}")
    cmd("crxReplayFailures", c["replay_failures"])
    cmd("crxCorrectnessInstances", c["instances_checked"])

    # --- E1 mechanism -----------------------------------------------------
    mech = {m["mode"]: m for m in rep["mechanism"]}
    for mode, tag in (("independent", "Indep"), ("joint", "Joint")):
        if mode not in mech:
            continue
        cmd(f"crxWidth{tag}", num(mech[mode]["mean_max_D_width"], 3))
        cmd(f"crxMeanWidth{tag}", num(mech[mode]["mean_mean_D_width"], 3))
        cmd(f"crxRootCertified{tag}", pct(mech[mode]["share_certified_at_root"]))
        cmd(f"crxDecisiveWidth{tag}", num(mech[mode]["median_winner_coordinate_width"], 1))
        cmd("crxDecisiveCategorical", mech[mode]["n_categorical_decisive"])
        cmd("crxDecisiveTotal", mech[mode]["n"])

    # --- E2 per-arm summary on the locked splits --------------------------
    tags = {
        "A0_global_independent": "ArmZero",
        "A1_decision_independent": "ArmOne",
        "A2_decision_joint": "ArmTwo",
        "A3_decision_joint_relevant": "ArmThree",
    }
    for row in rep["splits"]:
        if row["split"] not in ("test", "stress"):
            continue
        s = "Test" if row["split"] == "test" else "Stress"
        t = tags[row["arm"]]
        cmd(f"crx{s}{t}Rho", num(row["mean_rho_lower"]))
        cmd(f"crx{s}{t}RhoMedian", num(row["median_rho_lower"]))
        cmd(f"crx{s}{t}Positive", pct(row["share_rho_positive"]))
        cmd(f"crx{s}{t}Volume", num(row["mean_focal_certified_volume"], 3))
        cmd(f"crx{s}{t}Certified", pct(row["share_focal_certified"]))
        cmd(f"crx{s}N", row["n_instances"])

    # --- primary contrasts ------------------------------------------------
    names = {"P1_decision_focus": "POne", "P2_dependency": "PTwo"}
    for row in rep["primary"]:
        t = names[row["contrast"]]
        cmd(f"crx{t}Mean", num(row["mean_difference"]))
        cmd(f"crx{t}Lo", num(row["ci_low"]))
        cmd(f"crx{t}Hi", num(row["ci_high"]))
        cmd(f"crx{t}Wins", row["wins"])
        cmd(f"crx{t}Losses", row["losses"])
        cmd(f"crx{t}Ties", row["ties"])
        cmd(f"crx{t}PSup", num(row["prob_superiority"], 3))
        cmd(f"crx{t}Holm", f"{row.get('holm_adjusted_p', float('nan')):.2e}")
        cmd(f"crx{t}N", row["n"])
    for row in rep["exploratory"]:
        if row["split"] != "test":
            continue
        if row["contrast"] == "E1_branching":
            cmd("crxBranchMean", num(row["mean_difference"]))
            cmd("crxBranchLo", num(row["ci_low"]))
            cmd("crxBranchHi", num(row["ci_high"]))
        if row["contrast"] == "E2_full_vs_baseline":
            cmd("crxFullMean", num(row["mean_difference"]))
            cmd("crxFullLo", num(row["ci_low"]))
            cmd("crxFullHi", num(row["ci_high"]))

    # --- E7 anytime -------------------------------------------------------
    # LaTeX control sequences cannot contain digits, so budgets are spelled out
    budget_word = {64: "Bsixtyfour", 256: "Btwofiftysix", 1024: "Bonezerotwofour"}
    for row in rep["anytime"]:
        tag = "ArmZero" if row["arm"].startswith("A0") else "ArmThree"
        word = budget_word.get(int(row["budget"]))
        if word is None:
            continue
        cmd(f"crxAnytime{tag}{word}", num(row["mean_certified_volume"], 3))

    # --- bracket ----------------------------------------------------------
    b = rep["bracket"]
    cmd("crxBracketWithWitness", b["n_with_witness"])
    cmd("crxBracketTotal", b["n_total"])
    cmd("crxBracketInversions", "0" if not b["any_inversion"] else "at least one")
    cmd("crxBracketMedian", num(b["median_bracket_width"], 3))

    # --- frozen examples --------------------------------------------------
    cmd("crxExampleALeaving", len(ex["boundary"]["candidates_leaving_cells"]))
    cmd("crxExampleBJointBoxes", ex["slack"]["joint"]["boxes"])
    cmd("crxExampleBIndepBoxes", f"{ex['slack']['independent']['boxes']:,}")
    cmd("crxExampleBIndepVolume", pct(ex["slack"]["independent"]["certified_volume"]))
    cmd("crxExampleCNominal", ex["switch"]["nominal_winner"])
    cmd("crxExampleCWitness", ex["switch"]["witness_winner_class"][0])
    cmd("crxExampleCLower", num(ex["switch"]["certified_radius_lower"]))
    cmd("crxExampleCUpper", num(ex["switch"]["witness_level"], 2))

    DEST.write_text("\n".join(lines) + "\n")
    print(f"wrote {len(lines) - 2} macros to {DEST}")

    # The manuscript's graphicspath is submission/figures/, so the generated
    # artwork is copied there rather than referenced across trees.
    figdir = ROOT.parent / "Manuscrit" / "submission" / "figures"
    figdir.mkdir(parents=True, exist_ok=True)
    copied = []
    for fig in sorted((ROOT / "analysis" / "figures").glob("*.pdf")):
        shutil.copy2(fig, figdir / fig.name)
        copied.append(fig.name)
    if not copied:
        raise SystemExit("no generated figures found; run analysis/make_report.py first")
    print("copied figures: " + ", ".join(copied))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
