"""Smart-grid 24-hour economic dispatch — a 6-objective stochastic decision case.

A simplified but self-contained model.  Decision: an hourly dispatch policy
parameterised by a preference vector over 10 generators (thermal, gas, hydro,
wind, solar, storage, ...).  Six conflicting objectives are evaluated over a
24-hour horizon with stochastic renewable availability:

    f1 cost            (USD,    min)
    f2 emissions       (tCO2,   min)
    f3 unreliability   (ENS,    min)   expected energy not served
    f4 ramping/delay   (MW,     min)   response sluggishness
    f5 non-renewable   (frac,   min)   1 - renewable fraction
    f6 peak demand gap (MW,     min)   peak-shaving shortfall

Candidate solutions are generated by sweeping dispatch preference vectors; each
candidate's objectives are the mean over `n_scenarios` Monte-Carlo renewable
scenarios (so the case is genuinely stochastic).  We then run every selection
method and emit LexPR's regret certificate.
"""
from __future__ import annotations
import os, json, re
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

from . import methods, metrics
from .figure_evidence import figure_provenance, write_sidecar
from .publication_figures import OKABE_ITO, publication_style

N_GEN = 10
HOURS = 24
OBJ_NAMES = [
    "cost",
    "emissions",
    "unreliability",
    "ramping",
    "non_renewable",
    "peak_gap",
]
OBJ_DISPLAY = {
    "f1": "cost",
    "f2": "emissions",
    "f3": "unreliability",
    "f4": "ramping wear",
    "f5": "non-renewable fraction",
    "f6": "peak stress",
}


def semantic_probe_label(label):
    if label == "mean(all)":
        return "grand mean"
    if label == "max(all)":
        return "grand maximum"
    if label in OBJ_DISPLAY:
        return OBJ_DISPLAY[label]
    match = re.fullmatch(r"(mean|max)\(([^)]+)\)", label)
    if not match:
        raise ValueError(f"unrecognized probe label: {label}")
    operation, members = match.groups()
    names = [OBJ_DISPLAY[item] for item in members.split(",")]
    return f"{operation}({', '.join(names)})"


# per-generator static attributes (cost $/MWh, emission tCO2/MWh, max MW,
# ramp limit MW/h, renewable flag, dispatchable flag)
_GEN = np.array(
    [
        # cost emis  cap  ramp ren disp
        [22, 0.95, 120, 40, 0, 1],  # coal
        [28, 0.90, 110, 45, 0, 1],  # coal2
        [40, 0.45, 90, 70, 0, 1],  # gas CCGT
        [55, 0.55, 60, 90, 0, 1],  # gas peaker
        [12, 0.00, 80, 60, 1, 1],  # hydro
        [5, 0.00, 100, 20, 1, 0],  # wind
        [4, 0.00, 120, 25, 1, 0],  # solar
        [6, 0.00, 90, 30, 1, 0],  # wind2
        [70, 0.10, 50, 99, 0, 1],  # storage discharge
        [35, 0.30, 70, 55, 0, 1],  # biomass
    ],
    dtype=float,
)


def _demand_profile():
    t = np.arange(HOURS)
    base = (
        380 + 120 * np.sin((t - 8) / 24 * 2 * np.pi) + 90 * np.exp(-((t - 19) ** 2) / 8)
    )  # evening peak
    return np.maximum(base, 250)


def _scenario_renewables(rng):
    t = np.arange(HOURS)
    solar = np.maximum(np.sin((t - 6) / 12 * np.pi), 0) * rng.uniform(0.6, 1.0)
    wind = 0.4 + 0.4 * rng.random(HOURS)
    return solar, wind


def evaluate_policy(pref, n_scenarios, rng):
    """pref: length-N_GEN nonneg preference (dispatch priority). Returns 6 objs."""
    pref = np.maximum(pref, 1e-6)
    pref = pref / pref.sum()
    demand = _demand_profile()
    cost = emis = ens = ramp = nonren = peakgap = 0.0
    for _ in range(n_scenarios):
        solar, wind = _scenario_renewables(rng)
        prev = np.zeros(N_GEN)
        ren_energy = tot_energy = 0.0
        for h in range(HOURS):
            cap = _GEN[:, 2].copy()
            # renewable availability scales solar/wind caps this hour
            cap[6] *= solar[h]  # solar
            cap[5] *= wind[h]
            cap[7] *= wind[h]  # wind
            want = pref * demand[h]
            disp = np.minimum(want, cap)
            # fill any residual demand greedily by remaining capacity
            resid = demand[h] - disp.sum()
            if resid > 0:
                head = cap - disp
                add = np.minimum(head, resid * head / (head.sum() + 1e-9))
                disp += add
            served = disp.sum()
            ens += max(demand[h] - served, 0.0)
            cost += float(disp @ _GEN[:, 0])
            emis += float(disp @ _GEN[:, 1])
            ramp += float(np.abs(disp - prev) @ (1.0 / _GEN[:, 3]))
            ren_energy += float(disp[_GEN[:, 4] == 1].sum())
            tot_energy += served
            prev = disp
        peakgap += max(
            demand.max() - (pref * demand.max() * (_GEN[:, 4] == 0)).sum(), 0
        )
        nonren += 1.0 - ren_energy / (tot_energy + 1e-9)
    k = n_scenarios
    return np.array(
        [cost / k / 1e3, emis / k, ens / k, ramp / k, nonren / k, peakgap / k / 1e2]
    )


def build_candidates(n_candidates=250, n_scenarios=20, seed=2024):
    rng = np.random.default_rng(seed)
    prefs = rng.dirichlet(np.ones(N_GEN) * 0.6, size=n_candidates)  # diverse
    F = np.array(
        [
            evaluate_policy(p, n_scenarios, np.random.default_rng(seed + i + 1))
            for i, p in enumerate(prefs)
        ]
    )
    from .problems import non_dominated

    # keep non-dominated for a clean efficient candidate set
    keep_mask = _nd_mask(F)
    if not keep_mask.any():
        raise RuntimeError("smart-grid model produced no non-dominated candidates")
    return F[keep_mask], prefs[keep_mask]


def _nd_mask(F):
    n = F.shape[0]
    keep = np.ones(n, bool)
    for i in range(n):
        if not keep[i]:
            continue
        dom = np.all(F <= F[i], axis=1) & np.any(F < F[i], axis=1)
        dom[i] = False
        if dom.any():
            keep[i] = False
    return keep


def run_case(outdir="results", seed=2024):
    F, prefs = build_candidates(seed=seed)
    rng = np.random.default_rng(seed)
    chosen = {}
    for name in ["TOPSIS", "CP", "Knee", "SMAA", "MMR", "LexPR"]:
        fn = methods.METHODS[name]
        chosen[name] = (
            fn(F, rng=np.random.default_rng(7))
            if name in ("SMAA", "MMR", "RW")
            else fn(F)
        )
    # held-out loss (mean and worst-case tail) for each method on this case
    cache = metrics.precompute_utilities(
        F, np.random.default_rng(123), n_per_family=600
    )
    loss = {
        name: metrics.loss_from_cache(cache, idx)[0] for name, idx in chosen.items()
    }
    tail = {
        name: metrics.loss_from_cache(cache, idx)[1] for name, idx in chosen.items()
    }
    # LexPR certificate
    idx, D, labels, _ = methods.lexpr(F, return_detail=True)
    cert = sorted(zip(labels, D[idx]), key=lambda kv: -kv[1])
    display_cert = [(semantic_probe_label(label), value) for label, value in cert]

    summary = dict(
        n_candidates=int(F.shape[0]),
        chosen={k: int(v) for k, v in chosen.items()},
        objectives_of_choice={k: F[v].round(3).tolist() for k, v in chosen.items()},
        held_out_loss={k: round(float(v), 4) for k, v in loss.items()},
        held_out_tail={k: round(float(v), 4) for k, v in tail.items()},
        certificate=[(lab, round(float(val), 3)) for lab, val in cert],
        display_certificate=[(lab, round(float(val), 3)) for lab, val in display_cert],
        obj_names=OBJ_NAMES,
    )
    os.makedirs(f"{outdir}/tables", exist_ok=True)
    with open(f"{outdir}/tables/smartgrid_summary.json", "w") as f:
        json.dump(summary, f, indent=2)

    # Complete, labelled certificate. The presentation binding band is not the
    # numerical selection tolerance and is reported separately.
    beta = 0.01
    values = np.array([value for _, value in display_cert], dtype=float)
    binding = values >= values.max() - beta
    colors = [
        OKABE_ITO["orange"] if is_binding else OKABE_ITO["blue"]
        for is_binding in binding
    ]
    os.makedirs(f"{outdir}/figures", exist_ok=True)
    certificate_path = Path(outdir) / "figures" / "certificate.pdf"
    with publication_style():
        fig, ax = plt.subplots(figsize=(7.2, 4.8))
        positions = np.arange(len(display_cert))[::-1]
        ax.barh(positions, values, color=colors)
        ax.set_yticks(positions, [label for label, _ in display_cert])
        ax.set_xlim(0, 1)
        ax.set_xlabel(r"normalised disappointment $D_q\in[0,1]$")
        ax.set_title(f"Smart-grid LexPR certificate (candidate {idx})")
        for position, value in zip(positions, values):
            ax.text(value + 0.012, position, f"{value:.3f}", va="center", fontsize=7)
        ax.text(
            0.99,
            0.02,
            r"binding band $\beta=0.01$; reporting tolerance $\tau=10^{-4}$",
            transform=ax.transAxes,
            ha="right",
            va="bottom",
            fontsize=7,
        )
        fig.tight_layout()
        fig.savefig(certificate_path)
        plt.close(fig)
    metadata = figure_provenance(
        Path(__file__).resolve().parents[2],
        run_id=None,
        params={
            "figure": "smartgrid_certificate",
            "seed": seed,
            "probe_family": "adaptive",
            "normalization": "empirical candidate-set bounds",
            "tau": 1e-4,
            "beta": beta,
        },
    )
    metadata.update(
        {
            "candidate_index": int(idx),
            "probe_count": len(display_cert),
            "omitted_probe_count": 0,
            "display_labels": [label for label, _ in display_cert],
            "binding_labels": [
                label
                for (label, _), is_binding in zip(display_cert, binding)
                if is_binding
            ],
        }
    )
    write_sidecar(certificate_path, metadata)

    # method comparison bar chart (mean vs worst-case held-out loss)
    with publication_style():
        fig, ax = plt.subplots(figsize=(6, 3))
        names = list(loss.keys())
        x = np.arange(len(names))
        w = 0.38
        ax.bar(
            x - w / 2,
            [loss[n] for n in names],
            w,
            label="mean loss",
            color=OKABE_ITO["sky"],
        )
        ax.bar(
            x + w / 2,
            [tail[n] for n in names],
            w,
            label="worst-case (tail) loss",
            color=OKABE_ITO["blue"],
        )
        ax.set_xticks(x)
        ax.set_xticklabels(names, rotation=30, fontsize=8)
        ax.set_ylabel("held-out loss (lower better)")
        ax.legend(fontsize=8)
        ax.set_title("Smart-grid: held-out decision loss by method", fontsize=9)
        fig.tight_layout()
        fig.savefig(f"{outdir}/figures/smartgrid_loss.pdf")
        plt.close(fig)
    return summary
