"""Recast the manuscript into Wiley's official LaTeX authoring template (USG.cls).

Produces `Manuscrit/wiley/`, a self-contained folder that compiles with
XeLaTeX against the class file shipped in `WileyDesign/Optimal-Design-layout/`.
The generated tree is what a Wiley typesetter receives: class file, supporting
styles, fonts, figures, `refs.bib`, the pre-built `.bbl`, and one `.tex` per
section.

What the recast does, and why
-----------------------------
* **Drops the local page furniture.** `geometry`, `fancyhdr`, `placeins`, the
  `\\topfraction` overrides and the custom `\\pagestyle` are removed: the
  guidelines forbid changing global spacing and layout, and the class owns them.
* **Uses the class's own theorem environments** instead of redeclaring
  `theorem`/`proposition`/`lemma`, which the guidelines list as something not to
  reintroduce.
* **Expands the generated `\\crx...` macros into literal numbers.** The
  guidelines ask that author macros be kept to an absolute minimum, and 100-odd
  generated control sequences would reach the typesetter as unresolvable. The
  values still come from `enhanced/results/` -- the expansion happens here, so
  the reproducibility chain is unbroken and the shipped source is plain.
* **Moves the Declarations block into the class's backmatter commands**
  (`\\bmsection*`), which is where Wiley expects author contributions, funding,
  conflicts, data availability and supporting information.
* **Ships the `.bbl`.** The `APA` class option selects `WileyNJD-APA.bst`, which
  is not distributed in this template package and is not installed here, so
  BibTeX cannot be rerun against it. The guidelines explicitly accept a `.bbl`;
  the apacite-generated one is supplied and `refs.bib` travels with it.

No anonymous variant is produced. The journal's author guidelines state that it
operates a single-blind peer review model, and its Main Text File requirements
call for the full names of the authors with their institutional affiliations, so
an anonymised main document would not satisfy them.

Single column is used deliberately. The guidelines state that the typesetter
converts to the journal's final specification regardless of the column format
chosen, and the wide tables and full-width figures in this paper are legible in
one column and would break in two.
"""
from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
M = ROOT / "Manuscrit"
S = M / "submission"
TEMPLATE = ROOT / "WileyDesign" / "Optimal-Design-layout"
OUT = M / "wiley"

SECTIONS = ["introduction", "related_work", "method", "properties", "computation",
            "certification", "experiments", "discussion"]

#: Preamble lines of the local build that the class owns and must not see.
STRIP_PATTERNS = [
    r"\\usepackage\[margin=3cm\]\{geometry\}",
    r"\\usepackage\{fancyhdr\}",
    r"\\usepackage\{placeins\}",
    r"\\usepackage\{caption\}",
    r"\\usepackage\{microtype\}",
    r"\\pagestyle\{fancy\}.*",
    r"\\setlength\{\\headheight\}.*",
    r"\\captionsetup.*",
    r"\\renewcommand\{\\topfraction\}.*",
    r"\\setcounter\{topnumber\}.*",
    r"\\newtheorem.*",
]

HEADER = r"""%% Journal of Multi-Criteria Decision Analysis -- research article.
%% Wiley standard PDF design, class file USG.cls.
%%
%% GENERATED by Manuscrit/scripts/build_wiley_version.py -- do not edit by hand.
%% Edit Manuscrit/main.tex and Manuscrit/submission/*.tex and re-run the script.
%%
%% Compile with XeLaTeX (the class ships STIX fonts in Fonts/).
%% The reference list is supplied as main.bbl: the APA class option selects
%% WileyNJD-APA.bst, which is not distributed with this template package.
%% refs.bib is included so the typesetter can regenerate it if needed.
\documentclass[APA]{USG}

\usepackage{array}
\graphicspath{{./figures/}{./images/}}

\articletype{RESEARCH ARTICLE}
\received{00 Month 0000}
\revised{00 Month 0000}
\accepted{00 Month 0000}
\journal{Journal of Multi-Criteria Decision Analysis}
\volume{00}
\copyyear{2026}
\startpage{1}
\articledoi{10.1002/mcda.0000}

\newcommand{\R}{\mathbb R}
\newcommand{\Q}{\mathcal Q}
\newcommand{\ideal}{z^\star}
\newcommand{\nadir}{z^{\mathrm{nad}}}

\begin{document}

\title{Resolution-Aware Lexicographic Tail-Regret Selection under Uncertain
Normalisation Bounds}

AUTHORBLOCK

\keywords{multicriteria decision analysis | lexicographic selection | regret |
conditional value-at-risk | normalisation uncertainty | robustness}

\abstract[ABSTRACT]{ABSTRACTTEXT}

\maketitle

"""

AUTHOR_BLOCK = r"""\author[1]{Madani Bezoui}[https://orcid.org/0000-0002-8342-7039]

\authormark{BEZOUI}
\titlemark{Resolution-aware tail-regret selection}

\address[1]{\orgdiv{CESI LINEACT, UR 7527, }\orgname{CESI, }%
\orgaddress{\state{Vand\oe uvre-l\`es-Nancy, }\country{France}}}

\corres{Madani Bezoui (\email{mbezoui@cesi.fr})}
"""


BACKMATTER = r"""
\bmsection*{Author Contributions}

\textbf{Madani Bezoui:} conceptualization; methodology; software; formal
analysis; investigation; visualization; writing -- original draft; writing --
review and editing.

\bmsection*{Acknowledgments}

This research received no external funding. No additional acknowledgments are
declared.

\bmsection*{Conflicts of Interest}

The author declares no conflicts of interest.

\bmsection*{Ethics Statement}

No human participants, animals or personal data were involved. The supplier
example is constructed.

\bmsection*{Data Availability Statement}

All scripts, generated candidate matrices, perturbation directions, the
protocol, per-instance results, statistical summaries, the certification
benchmark with its raw results, and figure sources accompany the submission as
supporting information, together with the UCI Energy Efficiency file under
CC BY 4.0 and its SHA-256 checksum. The UCI dataset is independently available
at \url{https://doi.org/10.24432/C51307}. The complete code and data archive is permanently deposited under the Concept DOI \url{https://doi.org/10.5281/zenodo.21771785} (which always resolves to the latest version), and the repository is \url{https://github.com/MadBezoui/ReLexTail}. It supersedes the
earlier and smaller release archived at \url{https://doi.org/10.5281/zenodo.21771786},
to which the experiments reported here must not be attributed.

\bibliography{refs}

\bmsection*{Supporting Information}

Additional supporting information can be found online in the Supporting
Information section. One archive contains the manuscript sources, the study and
certification code, the protocol and claim registry, the raw per-instance
results and every figure source, with a single reproduction command.

\end{document}
"""



def macro_table() -> dict:
    """The generated certification numbers, name -> literal value."""
    src = (S / "generated_certrelex.tex").read_text()
    table = dict(re.findall(r"\\newcommand\{\\(crx[A-Za-z]+)\}\{([^}]*)\}", src))
    if not table:
        raise SystemExit(
            "no macros found in submission/generated_certrelex.tex; "
            "run enhanced/reproduce.py first"
        )
    return table


def expand(text: str, table: dict) -> str:
    """Replace every `\\crxName` / `\\crxName{}` with its literal value."""
    def sub(m):
        name = m.group(1) or m.group(2)
        if name not in table:
            raise SystemExit(f"undefined generated macro in the sources: \\{name}")
        return table[name]

    out = re.sub(r"\\(crx[A-Za-z]+)\{\}|\\(crx[A-Za-z]+)", sub, text)
    # Only a *control sequence* counts: label names such as fig:crxmechanism
    # legitimately contain the same three letters.
    leftover = re.findall(r"\\crx[A-Za-z]+", out)
    if leftover:
        raise SystemExit(f"generated macros survived expansion: {sorted(set(leftover))}")
    return out


def section_text(name: str, table: dict) -> str:
    text = (S / f"{name}.tex").read_text()
    if name == "discussion":
        # The Declarations block becomes the class's backmatter commands.
        marker = r"\section*{Declarations}"
        if marker not in text:
            raise SystemExit("Declarations block not found in discussion.tex")
        text = text.split(marker)[0].rstrip() + "\n"
    text = text.replace(r"\FloatBarrier", "")
    # The class loads NJDapacite in `apaciteclassic` mode, which does not
    # provide natbib's \citep / \citet.  The guidelines' own example uses
    # \cite, and under apaciteclassic \cite already renders as
    # "(Author, year)", which is what \citep produced locally.
    text = text.replace(r"\citep{", r"\cite{").replace(r"\citet{", r"\citeA{")
    return expand(text, table)


def figure_legends(table: dict) -> str:
    """A complete list of figure legends, in the text.

    Required by the journal: "Figure legends must be added beneath each
    individual image during upload AND as a complete list in the text."  The
    captions are re-read from the same section files that typeset them in this
    same run, so the list cannot drift from the figures.
    """
    text = "\n".join((S / f"{name}.tex").read_text() for name in SECTIONS)
    captions, pos = [], 0
    while True:
        start = text.find(r"\caption{", pos)
        if start < 0:
            break
        i = start + len(r"\caption{")
        begin, depth = i, 1
        while depth:
            if text[i] == "{" and text[i - 1] != "\\":
                depth += 1
            elif text[i] == "}" and text[i - 1] != "\\":
                depth -= 1
            i += 1
        cap, pos = text[begin:i - 1], i
        before = text[:start]
        if before.rfind(r"\begin{figure}") > before.rfind(r"\begin{table}"):
            captions.append(expand(cap, table))
    if not captions:
        raise SystemExit("no figure captions found")
    body = [r"\bmsection*{Figure Legends}", ""]
    for i, cap in enumerate(captions, 1):
        body.append(r"\noindent\textbf{Figure %d.}~%s\par\vspace{6pt}" % (i, cap))
    return "\n".join(body)


def abstract_text(table: dict) -> str:
    src = (M / "main.tex").read_text()
    body = src.split(r"\begin{abstract}")[1].split(r"\end{abstract}")[0].strip()
    return expand(body, table)


def copy_template(out: Path) -> None:
    for pattern in ("*.cls", "*.sty", "*.bst", "*.STY"):
        for f in TEMPLATE.glob(pattern):
            shutil.copy2(f, out / f.name)
    shutil.copytree(TEMPLATE / "Fonts", out / "Fonts")
    # The class draws the Wiley logo, ORCID mark and open-access badges on the
    # first page, so its images/ folder is part of the template, not decoration.
    shutil.copytree(TEMPLATE / "images", out / "images")
    neutralise_specimen_marks(out / "images")
    for name in ("empty.eps", "box.eps"):
        src = TEMPLATE / name
        if src.exists():
            shutil.copy2(src, out / name)


BLANK_EPS = """%!PS-Adobe-3.0 EPSF-3.0
%%BoundingBox: 0 0 1 1
%%HiResBoundingBox: 0 0 1 1
%%Creator: build_wiley_version.py
%%Title: intentionally blank
%%EndComments
%%EOF
"""


def neutralise_specimen_marks(images: Path) -> None:
    """Blank out two marks the class draws that would be false on this article.

    `USG.cls` hardcodes the specimen journal's cover strip (`allergy.eps`) on the
    title page and an OPEN ACCESS badge (`images/openaccess`) beside the article
    type.  Neither is true here: the target journal is different, and the open
    access decision has not been made.  The class itself is left untouched --
    the guidelines say not to alter it -- so the two image files are replaced by
    a blank one instead.  Restoring either mark is a matter of copying the
    original file back from the template folder.
    """
    for stem in ("allergy", "openaccess"):
        eps = images / f"{stem}.eps"
        eps.write_text(BLANK_EPS)
        converted = images / f"{stem}-eps-converted-to.pdf"
        if converted.exists():
            converted.unlink()
        r = subprocess.run(["epstopdf", eps.name, f"--outfile={stem}-eps-converted-to.pdf"],
                           cwd=images, capture_output=True, text=True)
        if r.returncode != 0:
            raise SystemExit(f"epstopdf failed on the blank {stem}.eps:\n{r.stderr}")


def compile_pdf(out: Path) -> Path:
    """Three XeLaTeX passes; BibTeX is deliberately not run (see the header)."""
    for i in range(3):
        r = subprocess.run(
            ["xelatex", "-interaction=nonstopmode", "-halt-on-error", "main.tex"],
            cwd=out, capture_output=True, text=True,
        )
        if r.returncode != 0:
            log = (out / "main.log")
            tail = log.read_text()[-4000:] if log.exists() else r.stdout[-4000:]
            raise SystemExit(f"XeLaTeX pass {i + 1} failed:\n{tail}")
    return out / "main.pdf"


def check(out: Path, pdf: Path) -> dict:
    """Hard gates.  Anything here that fails stops the build."""
    log = (out / "main.log").read_text()
    text = subprocess.run(["pdftotext", str(pdf), "-"],
                          capture_output=True, text=True).stdout
    problems = []
    if re.search(r"Reference .* undefined", log):
        problems.append("undefined references")
    if re.search(r"Citation .* undefined", log):
        problems.append("undefined citations")
    if "??" in text:
        problems.append("unresolved cross-reference printed as ??")
    if re.search(r"\\crx[A-Za-z]+", (out / "main.tex").read_text()):
        problems.append("unexpanded generated macro")

    figures = sorted({int(n) for n in re.findall(r"F I G U R E (\d+)", text)})
    tables = sorted({int(n) for n in re.findall(r"T A B L E (\d+)", text)})
    expected_figures = sum(
        (out / "sections" / f"{name}.tex").read_text().count(r"\includegraphics")
        for name in SECTIONS
    )
    if figures != list(range(1, expected_figures + 1)):
        problems.append(f"figures numbered {figures}, expected 1..{expected_figures}")
    if not tables or tables != list(range(1, len(tables) + 1)):
        problems.append(f"tables numbered {tables}")

    if problems:
        raise SystemExit("Wiley build has problems: " + "; ".join(problems))

    pages = subprocess.run(["pdfinfo", str(pdf)], capture_output=True, text=True).stdout
    return {
        "pages": int(re.search(r"Pages:\s+(\d+)", pages).group(1)),
        "figures": len(figures),
        "tables": len(tables),
        "overfull": len(re.findall(r"Overfull \\hbox \((\d+)", log)),
    }


def build(out: Path) -> dict:
    if not (TEMPLATE / "USG.cls").exists():
        raise SystemExit(f"Wiley template not found at {TEMPLATE}")
    table = macro_table()

    if out.exists():
        shutil.rmtree(out)
    (out / "sections").mkdir(parents=True)
    (out / "figures").mkdir()

    copy_template(out)
    shutil.copy2(M / "refs.bib", out / "refs.bib")
    shutil.copy2(M / "main.bbl", out / "main.bbl")
    for fig in S.glob("figures/*.pdf"):
        shutil.copy2(fig, out / "figures" / fig.name)

    for name in SECTIONS:
        (out / "sections" / f"{name}.tex").write_text(section_text(name, table))

    body = HEADER.replace("ABSTRACTTEXT", abstract_text(table))
    body = body.replace("AUTHORBLOCK", AUTHOR_BLOCK)
    body += "\n".join(f"\\input{{sections/{name}}}" for name in SECTIONS)
    backmatter = BACKMATTER
    body += "\n" + backmatter
    (out / "main.tex").write_text(body)

    print("compiling with XeLaTeX ...", flush=True)
    pdf = compile_pdf(out)
    stats = check(out, pdf)
    print(
        f"  {out.relative_to(M)}/main.pdf: {stats['pages']} pages, "
        f"{stats['figures']} figures, {stats['tables']} tables, "
        f"{stats['overfull']} overfull boxes"
    )
    return stats


def main() -> int:
    build(OUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
