"""Package only current sources, figures, data and required library sources."""
from pathlib import Path
import re,zipfile,hashlib,json
ROOT=Path(__file__).resolve().parents[2];M=ROOT/'Manuscrit';S=M/'submission'
sections=['introduction','related_work','method','properties','computation','certification','experiments','discussion']
text='\n'.join((S/(f+'.tex')).read_text() for f in sections)
# Match balanced caption braces so mathematical groups are retained.
legends=[];pos=0
while True:
    start=text.find('\\caption{',pos)
    if start<0:break
    i=start+len('\\caption{');begin=i;depth=1
    while depth:
        if text[i]=='{' and text[i-1]!='\\':depth+=1
        elif text[i]=='}' and text[i-1]!='\\':depth-=1
        i+=1
    cap=text[begin:i-1];pos=i
    # Figures only: the most recent begin environment identifies its type.
    preceding=text[:start];f=preceding.rfind('\\begin{figure}');t=preceding.rfind('\\begin{table}')
    if f>t:legends.append(cap)
# Legends are uploaded as plain text to the journal portal, so the generated
# certification macros are expanded here; an unexpanded \crx... would reach the
# editor as literal LaTeX.
macros=dict(re.findall(r'\\newcommand\{\\(crx[A-Za-z]+)\}\{([^}]*)\}',(S/'generated_certrelex.tex').read_text()))
def expand(cap):
    cap=re.sub(r'\\(crx[A-Za-z]+)\{\}|\\(crx[A-Za-z]+)',
               lambda m:macros[m.group(1) or m.group(2)],cap)
    assert 'crx' not in cap, f'unexpanded macro in caption: {cap[:80]}'
    return cap
legends=[expand(c) for c in legends]
(S/'figure_legends.txt').write_text('\n\n'.join(f'Figure {i+1}. {cap}' for i,cap in enumerate(legends))+'\n')
assert len(legends)==15, f'expected 15 figure captions, found {len(legends)}'
paths=[M/'main.tex',M/'main.pdf',M/'refs.bib']
paths+=list((M/'scripts').glob('*.py'))
paths+=list((M/'tests').glob('*.py'))+[M/'requirements.txt']
paths+=list(S.glob('*.tex'));paths=[p for p in paths if not p.name.startswith('original_')]
paths+=list(S.glob('*.md'))+list(S.glob('*.txt'))+list(S.glob('*.csv'))
paths+=list((S/'data').rglob('*'))+list((S/'figures').glob('*.pdf'))
paths+=list((ROOT/'Experimental/code/lexpr').rglob('*.py'))
# The certification section is generated by the enhanced/ tree; ship its
# sources, protocol, literature registry and raw results with the package.
paths+=list((ROOT/'enhanced/src').rglob('*.py'))+list((ROOT/'enhanced/analysis').glob('*.py'))
paths+=list((ROOT/'enhanced/tests').glob('*.py'))+[ROOT/'enhanced/reproduce.py',ROOT/'enhanced/README.md']
paths+=list((ROOT/'enhanced/protocol').glob('*'))+list((ROOT/'enhanced/literature').glob('*'))
paths+=list((ROOT/'enhanced/configs').glob('*'))+list((ROOT/'enhanced/baselines').glob('*'))+[ROOT/'README.md']
paths+=list((ROOT/'enhanced/results').glob('*'))+list((ROOT/'enhanced/analysis/tables').glob('*.csv'))
manifest={str(p.relative_to(ROOT)):hashlib.sha256(p.read_bytes()).hexdigest() for p in paths if p.is_file()}
(S/'manifest.sha256.json').write_text(json.dumps(manifest,indent=2))
paths.append(S/'manifest.sha256.json')
with zipfile.ZipFile(M/'JMCDA_submission.zip','w',zipfile.ZIP_DEFLATED) as z:
    for p in paths:
        if p.is_file():z.write(p,p.relative_to(ROOT))
with zipfile.ZipFile(M/'JMCDA_submission.zip') as z:assert z.testzip() is None
print(f'Packaged {len(paths)} files; {len(legends)} separate vector figures; ZIP integrity checked.')
