"""Regenerate the broadened-protocol CD diagram (Figure 2 / cd_protocol.pdf).

This script redraws the diagram dynamically from the raw parquet records
generated by the protocol validation, using the correct Nemenyi CD, matching
the lexpr.experiments._cd_diagram style.
"""

import os
import pandas as pd
import numpy as np
import sys

# Ensure lexpr is in the path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from lexpr import stats
from lexpr.figure_evidence import (
    evidence_metadata,
    figure_provenance,
    load_protocol_evidence,
    write_sidecar,
)
from lexpr.publication_figures import render_cd_diagram

# 1. Load the immutable manuscript-approved protocol run.
REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
evidence = load_protocol_evidence(REPO_ROOT)
parquet_path = evidence.raw_path

df = pd.read_parquet(parquet_path)
pivot = df.pivot_table(
    index=["seed", "geometry", "m", "replication", "dirichlet_alpha"],
    columns="method",
    values="tail_loss",
)

methods = list(evidence.method_names)
pivot = pivot.reindex(columns=methods)
mat = pivot.values

# 2. Compute true ranks and CD
ranks = stats.average_ranks(mat)
k = len(methods)
N = mat.shape[0]
CD = stats.nemenyi_cd(k, N, alpha=0.05)
if not np.isclose(CD, evidence.nemenyi_cd):
    raise ValueError(f"computed CD {CD} does not match evidence {evidence.nemenyi_cd}")

RANKS = dict(zip(methods, ranks))
if not all(np.isclose(RANKS[name], evidence.average_ranks[name]) for name in methods):
    raise ValueError("computed ranks do not match authoritative analysis")

print(f"Generated CD Diagram for {k} methods and {N} instances. CD = {CD:.3f}")

targets = [
    os.path.join(REPO_ROOT, "paper", "cd_protocol.pdf"),
    os.path.join(REPO_ROOT, "results", "protocol", "figures", "cd_protocol.pdf"),
]

for t in targets:
    t = os.path.abspath(t)
    os.makedirs(os.path.dirname(t), exist_ok=True)
    render_cd_diagram(
        evidence.average_ranks,
        evidence.nemenyi_cd,
        t,
        title="Tail held-out loss ranks: frozen broadened protocol",
    )
    metadata = figure_provenance(
        REPO_ROOT,
        run_id=evidence.run_id,
        params={
            "figure": "cd_protocol",
            "evidence": evidence_metadata(evidence),
        },
    )
    write_sidecar(t, metadata)
    print("wrote", t)
