"""Export the two supplier-case witness bound vectors (MC3, second request).

The exact possible-winner set of the supplier case at a 2% bound box is closed
from both sides: certified elimination removes eight of the ten suppliers, and
membership of the two survivors is established by explicit WITNESSES, that is,
by admissible bound vectors at which each of them is the exact LexPR winner.

Until now the manuscript only asserted that those witnesses exist and were
archived.  This script writes them out in full, so a reader can re-evaluate the
rule at each printed vector and confirm the reported winner independently.

Witness 1 is the nominal bound vector (the active ideal and nadir of the
shortlist), at which S7 wins.
Witness 2 is a bound vector inside the box at which S1 wins.  It is found by a
deterministic scan of the declared perturbation model at increasing levels,
taking the FIRST configuration encountered under the archived seed, so the
result is reproducible rather than hand-picked.

Outputs
    scripts/real_results/witness_bounds.json
    manuscript/generated/witness_bounds.tex

Usage
    python scripts/run_witness_bounds.py
"""
from __future__ import annotations

import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)

from lexpr import certified, methods, supplier  # noqa: E402

SEED = 20260628
OUTDIR = os.path.join(HERE, "real_results")
TEXDIR = os.path.abspath(os.path.join(ROOT, "..", "manuscript", "generated"))

CRIT_SHORT = ["Cost", "Defects", "Lead", "GHG", "Energy", "Social", "Resil."]


def winner_at(F, probes, ideal, nadir):
    """Exact finite LexPR winner at one explicit bound vector."""
    r = (F - ideal) / (nadir - ideal)
    cols = []
    for kind, idx in probes:
        idx = list(idx)
        if kind == "single":
            v = r[:, idx[0]]
        elif kind == "mean":
            v = r[:, idx].mean(axis=1)
        else:
            v = r[:, idx].max(axis=1)
        a, b = v.min(), v.max()
        cols.append((v - a) / (b - a) if b > a else np.zeros_like(v))
    D = np.column_stack(cols)
    return methods.leximax_argmin(D), D


def find_reversal_witness(F, probes, nominal, seed=SEED):
    """First bound vector under the declared model at which a rival wins."""
    ideal0, nadir0 = F.min(axis=0), F.max(axis=0)
    m = F.shape[1]
    for p in np.arange(0.001, 0.061, 0.001):
        rng = np.random.default_rng(seed + int(round(p * 1000)))
        for _ in range(5000):
            up = rng.uniform(0.0, p, size=m)
            u = rng.uniform(-p, p, size=m)
            ideal = ideal0 * (1.0 - up)
            nadir = np.maximum(nadir0 * (1.0 + u), ideal + 1e-3)
            w, _ = winner_at(F, probes, ideal, nadir)
            if w != nominal:
                return float(round(p, 4)), int(w), ideal, nadir
    return None, None, None, None


def main():
    F, names, crit = supplier.load_supplier_case()
    probes, labels = certified.canonical_supplier_probes()
    nominal = methods.lexpr(F, theta=0.6)
    ideal0, nadir0 = F.min(axis=0), F.max(axis=0)

    w0, D0 = winner_at(F, probes, ideal0, nadir0)
    assert w0 == nominal, "nominal witness does not reproduce the nominal winner"

    p, rival, ideal1, nadir1 = find_reversal_witness(F, probes, nominal)
    if rival is None:
        raise SystemExit("no reversal witness found in the scanned range")
    w1, _ = winner_at(F, probes, ideal1, nadir1)
    assert w1 == rival

    res = {
        "seed": SEED,
        "criteria": crit if isinstance(crit, list) else CRIT_SHORT,
        "nominal_winner": names[nominal],
        "witness_nominal": {
            "winner": names[nominal],
            "level": 0.0,
            "ideal": [float(x) for x in ideal0],
            "nadir": [float(x) for x in nadir0],
        },
        "witness_reversal": {
            "winner": names[rival],
            "level": p,
            "ideal": [float(x) for x in ideal1],
            "nadir": [float(x) for x in nadir1],
            "ideal_rel_dev_pct": [float(100.0 * (a / b - 1.0))
                                  for a, b in zip(ideal1, ideal0)],
            "nadir_rel_dev_pct": [float(100.0 * (a / b - 1.0))
                                  for a, b in zip(nadir1, nadir0)],
        },
    }

    os.makedirs(OUTDIR, exist_ok=True)
    with open(os.path.join(OUTDIR, "witness_bounds.json"), "w") as f:
        json.dump(res, f, indent=2)

    write_table(res)
    print(json.dumps({k: v for k, v in res.items() if k != "criteria"}, indent=2))
    print(f"\nnominal witness -> {names[nominal]}; "
          f"reversal witness at p={p:.3f} -> {names[rival]}")


def write_table(res):
    crit = CRIT_SHORT
    a = res["witness_nominal"]
    b = res["witness_reversal"]
    rows = [
        "% Auto-generated by scripts/run_witness_bounds.py. Do not edit.",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\begin{tabular}{@{}l" + "r" * len(crit) + "@{}}",
        "\\toprule",
        " & " + " & ".join(crit) + "\\\\",
        "\\midrule",
        "\\multicolumn{%d}{@{}l}{\\emph{Witness 1: nominal bounds, winner %s}}\\\\"
        % (len(crit) + 1, a["winner"]),
        "$z^{\\star}$ & " + " & ".join(f"{x:.3f}" for x in a["ideal"]) + "\\\\",
        "$z^{\\mathrm{nad}}$ & " + " & ".join(f"{x:.3f}" for x in a["nadir"]) + "\\\\",
        "\\addlinespace",
        "\\multicolumn{%d}{@{}l}{\\emph{Witness 2: reversal at $p=%.1f\\%%$, winner %s}}\\\\"
        % (len(crit) + 1, b["level"] * 100, b["winner"]),
        "$z^{\\star}$ & " + " & ".join(f"{x:.3f}" for x in b["ideal"]) + "\\\\",
        "$z^{\\mathrm{nad}}$ & " + " & ".join(f"{x:.3f}" for x in b["nadir"]) + "\\\\",
        "\\addlinespace",
        "dev.\\ $z^{\\star}$ (\\%) & "
        + " & ".join(f"{x:+.2f}" for x in b["ideal_rel_dev_pct"]) + "\\\\",
        "dev.\\ $z^{\\mathrm{nad}}$ (\\%) & "
        + " & ".join(f"{x:+.2f}" for x in b["nadir_rel_dev_pct"]) + "\\\\",
        "\\bottomrule",
        "\\end{tabular}",
    ]
    os.makedirs(TEXDIR, exist_ok=True)
    with open(os.path.join(TEXDIR, "witness_bounds.tex"), "w") as f:
        f.write("\n".join(rows) + "\n")
    print("wrote generated/witness_bounds.tex")


if __name__ == "__main__":
    main()
